version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  url-shortener:
    build: .
    container_name: url_shortener
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - app/.env

volumes:
  pgdata:
